### ISSUE TITLE
 RrwebPlayer iframe does not reproduce site code

### ISSUE THREAD

**Issue by waldirjunior** [rrweb-io/rrweb#101]
I am testing the project, and using rrweb-player. I can play actions on mouse, but iframe doesn't display site content

<iframe sandbox="allow-same-origin" scrolling="no"></iframe>

Could you help me understand?

**Comment by Yuyz0112** [comment]
@waldirjunior Could you provide your events for debugging?

**Comment by waldirjunior** [comment]
Yes!

![image](https://user-images.githubusercontent.com/33125898/61810432-9d699780-ae15-11e9-8c09-7b3499ef60ca.png)

**Comment by waldirjunior** [comment]
![Captura de Tela_Área de Seleção_20190724132342](https://user-images.githubusercontent.com/33125898/61810741-487a5100-ae16-11e9-9b78-8ae86efb8d27.png)

Link: https://teste-waldirmauriciojr484151.codeanyapp.com/novo/

**Comment by waldirjunior** [comment]
My 
![minha-tela](https://user-images.githubusercontent.com/33125898/61818459-44a2fa80-ae27-11e9-8c7b-a69bcee8633d.png)
_________________________
https://www.rrweb.io/replay
![tela-dele](https://user-images.githubusercontent.com/33125898/61818486-4ff62600-ae27-11e9-95b9-c2f67c661f19.png)

**Comment by Yuyz0112** [comment]
@waldirjunior do you mean you have a nested iframe in your site?

Recording iframe is still a [WIP](https://github.com/rrweb-io/rrweb/pull/68)

**Comment by waldirjunior** [comment]
@Yuyz0112  no, rrwebPlayer does not load iframe without video

![Captura de Tela_Área de Seleção_20190725141339](https://user-images.githubusercontent.com/33125898/61894305-88106e00-aee6-11e9-9d84-a17d1977cb69.png)

**Comment by bobsam** [comment]
Is this problem solved? Thanks~

**Comment by Pinchanzee** [comment]
Without testing this looks like your events are in the wrong order.  I had the same issue that boiled down to a race condition when storing events.  The first request takes longer because it contained the page DOM, so it can lead to type 3 events coming before the setup type 1,2,4,0 events.

I had similar symptoms which I fixed by ordering the requests by their timestamp, which leads to the 1,2,4,0 type events coming first.
The docs should definitely make reference to the fact that the replaying events have to be output in the same order they were emitted.

**Comment by shivamtomar96** [comment]
HI I am still facing the issue rrweb is not loading iframe/ video with content.

**Comment by Yuyz0112** [comment]
@shivamtomar96 are you using v1.0+ and recording iframe with same origin?

**Comment by shivamtomar96** [comment]
> @shivamtomar96 are you using v1.0+ and recording iframe with same origin?

No, I am using v 0.9.14 and origin are different.

**Comment by Yuyz0112** [comment]
@shivamtomar96 cross-origin iframe is not supported yet.
