### ISSUE TITLE
[Bug]: iframe element is not rendered with rrweb

### ISSUE THREAD

**Issue by annguyenprodev** [rrweb-io/rrweb#1071]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

2.0.0-alpha.4

### Expected Behavior

Successful rendering of iframe

### Actual Behavior

The iframe is not rendered, it's a blank space

### Steps to Reproduce

Record with rrweb as an extension on this page, but it didn't render iframe. Iframe position is a blank space
Link: https://login.salesforce.com/

![image](https://user-images.githubusercontent.com/67452313/206358790-8b64ab30-a4a2-420a-a6ab-d5ca0055d14b.png)

Even when I tried loading these events into https://rrwebdebug.com, it was not shown
https://rrwebdebug.com/play/index.html?url=http%3A%2F%2Fjsonblob.com%2F1050278044325134336&version=1.0.0-alpha.4&canvas=on&play=on

![image](https://user-images.githubusercontent.com/67452313/206360893-72317b0f-cf9f-4332-b815-6f2940280ea5.png)

Any solution for this issue? Thank you!

**Comment by thatsnotright** [comment]
I believe in this case the right side iframe counts as a cross-domain IFrame as it does not adhere to the Same-Origin policy (it's served from https://c.salesforce.com/login-messages/promos.html whereas the left is content from login.salesforce.com).

In this case the behavior is as expected, unless you inject rrweb in to every frame (using content_script's settings in manifest.json such as
`        matches: ['<all_urls>', '*://*/*'],
        "all_frames": true,`

and enable the `    recordCrossOriginIframes: true,` setting for your webextension so that it will get injected in to all iframes.

**Comment by annguyenprodev** [comment]
Thank you very much. You're right. That's a good solution for me
