### ISSUE TITLE
Requests for webfonts within player iframe can fail due to lack of CORS policy

### ISSUE THREAD

**Issue by eoghanmurray** [rrweb-io/rrweb#144]
Testing out rrweb on my site I can see that webfonts which are linked to from within the iframe player fail to load due to CORS policy.

```
Access to font at 'https://target.example.com/static/fonts/my-webfont.ttf' 
from origin 'https://rrweb-player.example.org' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I can access the font file if I directly request it using `wget` from my `rrweb-player.example.org` server, so I guess one solution will be to search for font resources in recordings, and replace them with a link to a proxied/downloaded version i.e. make them available at `https://rrweb-player.example.org/target-example-com-static-fonts-my-webfont.ttf`.

Is there any other solution possible, e.g. the same way that the player inlines CSS resources via `getCssRulesString` in case they are not accessible within the iframe?

**Comment by Yuyz0112** [comment]
Yes, you are right, download the static resource and replace the link is a possible solution.

I think there is no way to inline static resource since its can be arbitrary binary format and we could not rebuild all of them in the browser.

Feel free to re-open this issue if you need further discussion.
