### ISSUE TITLE
Live Mode, Observer View, How to sync the observer person's screen

### ISSUE THREAD

**Issue by randy-johnson** [rrweb-io/rrweb#239]
Hello,

I have 2 people:

Person1 - This person's screen is being recorded using live view.  events are being pushed to a node server where they are being stored in the database as well as being emitted to Person2.

Person 2.  - This person has a view only mode.  He is watching Person1's screen using live mode in the rrweb player .  Events are being received through socket.io

The problem I am having here is what to do when Person2 is not running the player when Person1 starts broadcasting events missing the snapshot event and any incremental snap shots.

If Person1 has been broadcasting for 10 minutes when Person2 files up live view.  What is the best way to get Person2 up to date with what is on Person1's screen.  

My first thought was to query the database when person2 connects and joins the socket channel but that could be thousands of events after 10 minutes.

Any thoughts on how I can accomplish getting Person2's screen up to date with Person1's so live view can continue?

My idea was perhaps I could trigger person one to send certain events (Perhaps a full snapshot or whatever event sends over the full page html)  when it received an emitted message from Person2 but it wasn't clear to me how to accomplish this.

**Comment by Yuyz0112** [comment]
Hi randy,

I think there are two questions in your screnaio. 

First, do you need to store Person1's session from the beginning persistently? If yes, the current approach is right. Otherwise if you only need to share session to Person2, you can start recording Person1's session when Person2 is ready. 

The other question is you need to implement a communication way between two person. Then Person2 can tell Person1 to do some actions. 

BTW, you do not need to query all the events history to catch up the session. You can simply start a new session with a full snapshot which represents the latest view.

**Comment by randy-johnson** [comment]
Thank you, that is helpful.

On your last comment

> BTW, you do not need to query all the events history to catch up the session. You can simply start a new session with a full snapshot which represents the latest view.

How would I start the new session with a full snapshot?

**Comment by Yuyz0112** [comment]
@randy-johnson I think stop and restart is the easiest way:

```js
let stopFn = record({
  emit
})

function whenRestart() {
  stopFn = record({
    emit
  })
}
```

**Comment by randy-johnson** [comment]
ok great.  Thank You.

**Comment by vvks** [comment]
@randy-johnson hi, i have a similar use-case, if you could help me with how are you running live mode in rrweb-player?

**Comment by vvks** [comment]
@randy-johnson hi, i found out about live mode. sorry for the trouble. thnx

**Comment by randy-johnson** [comment]
@vvks cool, no trouble, glad you found live mode
