### ISSUE TITLE
如何才能知道正在emit录制？

### ISSUE THREAD

**Issue by yubuting** [rrweb-io/rrweb#396]
目前想要正在是否录制emit，如果正在录的话就把它给停了

**Comment by Yuyz0112** [comment]
这样封装一下？

```js
let stopFn = null

function startRecord() {
  if (stopFn) {
    stopFn()
  }
  stopFn = record({
    emit() {}
  })
}

```

**Comment by yubuting** [comment]
好的，感谢，我目前也是这么加的

**Comment by yshzore** [comment]
为什么我在vue的mounted里进行录制，emit会一直执行，哪怕页面都没有变化，也没有任何点击

**Comment by Mark-Fenng** [comment]
鼠标移动等等很多变化也会触发emit的执行

**Comment by 961998264** [comment]
> emit会一直执行

这个问题我也碰到了，在h5页面中，与鼠标无关。页面元素也没变化，但是emit无限触发，直接导致内存溢出页面卡死。在次强调，与页面元素无关，也无鼠标移动。我一开始怀疑是我console.log引起的。但是排查了一下，并且去除了所有console还是没用

**Comment by yshzore** [comment]
我的问题找到了，当时我们的h5页面是放在客户端里的，所以为了调试方便用了vconsole，就是它导致页面卡死。在emit里使用了console，vconsole被触发更新了，导致了二者死循环，后来把vconsole 加上忽略的classname就解决问题了---- 回复的原邮件 ***@***.***>发送日期2022年01月20日 15:27 ***@***.***> ***@***.******@***.***>主题Re: [rrweb-io/rrweb] 如何才能知道正在emit录制？ (#396)



emit会一直执行



这个问题我也碰到了，在h5页面中，与鼠标无关。页面元素也没变化，但是emit无限触发，直接导致内存溢出页面卡死。在次强调，与页面元素无关，也无鼠标移动。我一开始怀疑是我console.log引起的。但是排查了一下，并且去除了所有console还是没用



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you commented.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/rrweb-io/rrweb/issues/396#issuecomment-1017190076",

"url": "https://github.com/rrweb-io/rrweb/issues/396#issuecomment-1017190076",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
