### ISSUE TITLE
Continue a recording and seeking in player

### ISSUE THREAD

**Issue by no-1ne** [rrweb-io/rrweb#420]
Hello Yu,
Thank you for the great library. 

we have users interacting on top of an existing recording. I.e replayer on the bg,  player can be paused and users can draw and explain on top of it. 

A hacky way is to run rrweb again within player iframe and save only relevant events.. but thats rrweb rebuild twice, once with player and again rrweb record 
 Can we initialise rrweb with an existing recordding json and start adding events from there(without having to rebuild again completely)  or can the sampling stategy be specific events

**Comment by eoghanmurray** [comment]
It sounds like you want to insert new events with a custom timestamp which is set to the current paused time of replay?
I don't see why there would be a separate rrweb recorder running during replay, e.g. presumably you *don't* want to record the entire editing experience (how a line was drawn or text was moved about while paused), but just the results of the annotation?  
An 'rrweb-annotate' project would be very cool, but I'm not sure how much it should build upon the recorder; it's kind of a separate layer on top right?

**Comment by startupgurukul** [comment]
Yes spot on, we need mousemove events with pen down or pen up based on that only pointer with tail (as already exists ) is shown or if pen down, annotations  are drawn in player.. this is a good reference point 

https://github.com/embiem/react-canvas-draw/blob/develop/src/index.js

**Comment by eoghanmurray** [comment]
Would you be happy if this was left out of scope?
I think you could achieve this by inserting custom events `rrwebRecord.addCustomEvent('annotation', payload)` whenever the user is finished annotating.  
These events could either identify a particular annotation, or included json or another structure that would embody the entire annotation.
You'd then need an event handler `replayer.on('custom-event', my_handler)` to re-add the annotation during replay.  
I'm not sure how/when you'd handle removal and/or transitions between annotations (how long an annotation should stay around & whether the next annotation should replace the previous), but I imagine that's specific to your application logic.

Anyhow if you get anything re-usable implemented, it might be a good candidate for a sister project — I'd definitely like to check it out.

**Comment by startupgurukul** [comment]
That's what we ended up doing but the lead to invoking rrweb.record again after player has rebuilt the snapshot was wondering if it can be avoided as if rrweb can start with snapshot available and skip having to rebuild the whole thing again adding mutation observers and all, so we are not blocked per se, just that want to remove the redundant mutation observers

Considering the change in player side needed we chose to seperate it and provide rrweb thing only for mouse and a player for mouse. Closing issue for now

**Comment by Yuyz0112** [comment]
I'm not sure whether the new [recipes](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/index.md) will give you some insipiration.

**Comment by eoghanmurray** [comment]
> invoking whole of rrweb.record again 

Why are you making another recording?  Is it because of `addCustomEvent`?  If that's the case, then maybe you could get away with `replayer.addEvent` which was originally intended for adding real-time events to the replayer (as they happen).

I've got a pull request which covers keeping events added via `addEvent` sorted by inserting them in the correct place (this was for a different reason):
https://github.com/rrweb-io/rrweb/pull/411

**Comment by startupgurukul** [comment]
That's a brilliant idea, by playing with tailconfig duration, will may have annotations as well

**Comment by startupgurukul** [comment]
Hello again folks, can we initialise rrweb record bypassing the snapshoting step, in our case  we are interested in the mouse movements, to remind you of the context, we can users replying on top of existing recording.

**Comment by eoghanmurray** [comment]
Hi @startupgurukul is this for the extra recording you are making to record annotations?
If you initialise the recording in an empty iframe that might do the trick (so that the snapshot step won't have much DOM state; just the empty iframe, and whatever you need to replay the pen-down movements?)
If you were to submit a patch which added an option to turn off DOM snapshotting, that might be accepted (I can't speak for the project maintainers), but I don't think anyone will do that for you unless there is some other use-case which I'm not thinking of.
Maybe what you are working on is suitable to become a sister-project, i.e. an annotations extension to the replayer?  Do you have any demos suitable for sharing?

**Comment by eoghanmurray** [comment]
> bypassing the snapshoting step
Is it not enough to just ignore those events when they are emitted?  Is it a performance thing?

**Comment by startupgurukul** [comment]
We did that initially skipping events other than mousemove, but mutation observer does take a toll. This is what we ended up doing  capture mouse movements save events in rrweb format 

To handle that customised rrweb player a lite version of player, we are handling mouse movements... Next is like you said  add drawing on top i.e pen/pencil. Currently it just has parity with current rrweb mouse behaviour (so nothing new yet to share), Will be happy to share a demo once we add the pen thingy
