### ISSUE TITLE
Wechat Mini Program is not supported in rrweb

### ISSUE THREAD

**Issue by myrider** [rrweb-io/rrweb#459]
Wechat Mini Program（微信小程序） is not supported in rrweb，How to solve it？Thank you very much.

**Comment by Yuyz0112** [comment]
I believe the WeChat mini-program is not using browser DOM under the hood, which rrweb uses for observing view changes.

So currently it's not possible to use rrweb in WeChat mini program(because it's not 'web'). In the future, maybe we can integrate rrweb with some high-level mini-program framework like Taro, which provides a virtualized DOM implementation.

**Comment by myrider** [comment]
Thank you very much for your reply.Can you have an indirect idea?

**Comment by Yuyz0112** [comment]
Not really, do not have any experience with WeChat mini-program development. Some input may be helpful.

**Comment by Yuyz0112** [comment]
Since this is not in a short-term plan, I'm going to close this issue.

Anyone interested in this can watch the repo for further development progress, or send a PR/issue to discuss the things we can start to do.

**Comment by vaynevayne** [comment]
@myrider 请问后面你实现了吗？
