### ISSUE TITLE
Recording only takes one full snapshot at the start and never again

### ISSUE THREAD

**Issue by divanvb** [rrweb-io/rrweb#517]
Hi

Not sure if I understand how the library works exactly. I start recordings and push all events to an array.
Once done, I submit that array to a server which then takes those events and plays it through rrweb-player but the problem is the player doesn't render correctly and the recording only shows blank pages. I know the snapshot should be type: 2 but as I said only at the start of the recording it takes one snapshot and never again.

This is how the Svelte component is rendered. Very strange.

![image](https://user-images.githubusercontent.com/17053486/111224320-f7206600-85e6-11eb-8043-ca1d4fa53235.png)

EDIT*
I did install rrweb-player via NPM. I just added the stylesheet manually to the index.html file and now it looks fine. Why does the styling not pull through from the installed package?

**Comment by MarcelReis** [comment]
The missing styles are probably caused by your bundle configuration. Try using the stylesheet, it should solve.
```html
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css"
/>
```

You can configure your recorder to take full snapshots with those parameter, `checkoutEveryNth` `checkoutEveryNms` check here the documentation
https://github.com/rrweb-io/rrweb/blob/master/guide.md#options
