### ISSUE TITLE
Scrubbing back breaks iFrames

### ISSUE THREAD

**Issue by ncaron** [rrweb-io/rrweb#535]
When using the scrubber to go back in the timeline, iFrames are getting destroyed. Going forward still works as intended.
Note that this happens with both players (the one in this repository and the one in rrweb-replayer)

Please see this recording to see it in action: https://share.getcloudapp.com/Jru4g2YZ

Steps to reproduce:
* Clone this repository and rrweb-replayer
* Build them locally
* Record a webpage with iFrames and save the events
* Copy the events and paste them in the code below
* Open the HTML page
  * iFrames are not visible (**bug**) 
  * Press play
    * iFrames are now visible and working
    * Skip forward in the timeline -> It still works
    * Go back in the timeline -> iFrames are getting destroyed (**bug**)

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="stylesheet" href="../rrweb-player/dist/style.css" />
  </head>
  <body>
    <div id="root"></div>

    <script src="../rrweb-player/dist/index.js"></script>
    <script>
      const events = [/* paste events here */];
      const element = document.querySelector("#root");
      const player = new rrwebPlayer({
        target: element,
        props: {
          autoPlay: false,
          events: events,
          blockClass: "rr-block",
          mouseTail: {
            duration: 1500,
            lineCap: "round",
            lineWidth: 3,
            strokeStyle: "red",
          },
        },
      });
    </script>
  </body>
</html>

```

**Comment by Mark-Fenng** [comment]
@ncaron Could you provide the events or the recorded website for debugging?

**Comment by ncaron** [comment]
@Mark-Fenng Sure! I added them in this pastebin: https://pastebin.com/jpVsz0wP

We have done a bit of digging and it seems that the following code from `src/replay/index.ts` line ~1116 is the source. On the second run, parent always exists and points to an old iFrame node and so `this.newDocumentQueue` is never refilled.

```typescript
let parent: INode | null | ShadowRoot = mirror.getNode(mutation.parentId);

if (!parent) {
  if (mutation.node.type === NodeType.Document) {
    // is newly added document, maybe the document node of an iframe
    return this.newDocumentQueue.push(mutation);
  }
}
```

Changing that block to the following seems to work in our case but is not yet fully tested so I didn't create a PR.

```typescript
let parent: INode | null | ShadowRoot = mirror.getNode(mutation.parentId);

if (
  mutation.node.type === NodeType.Document &&
  (!parent || !this.firstPlay && isIframeINode(parent))
) {
  // is newly added document, maybe the document node of an iframe
   return this.newDocumentQueue.push(mutation);
}

if (!parent) {
  return queue.push(mutation);
}
```

**Comment by Yuyz0112** [comment]
Hi @ncaron, I've done some debugging and find the root cause.

When designing the iframe nest recording feature, we choose to emit the attach iframe event when it's loaded. Generally, this works fine, but an iframe with empty src(local iframe) will perform various depends on browsers. Most of the time, the local iframe will be loaded in sync which causes its event to have a smaller timestamp than the full snapshot.

e.g:

```
event1: attach iframe-1 to node-1      @t0
event2: fullsnapshot contains node-1   @t1
```

So this is why `newDocumentQueue` was introduced to solve problems. When we replay event1, node1(iframe-1's parent) was not rebuilt, so we will store event1 in the queue. And after the replay event2, we will refill the event1 so iframe-1 will be attached.

And scrubbing back is a corner case. When scrubbing back, we will replay event1 and event2 in the order of timestamp again. But at this moment, the DOM is *dirty* because event1 and event2 have been cast.

Generally, we rely on the rebuilding of the full snapshot to reset DOM, but in this case, event2 will replay after the event1. So DOM was not reset when we scrubbing back to the event1.

I think the most straightforward fix is we should reset the DOM in a better timing, such as calling `setupDOM` when scrubbing back or add a generation mark to the DOM.

I will update the solution ASAP.

**Comment by ghempton** [comment]
We seem to be encountering this as well. Was the solution every altered to solve for this?
