### ISSUE TITLE
Feature Request: option to strip noscript tags

### ISSUE THREAD

**Issue by ucjonathan** [rrweb-io/rrweb#541]
We've notice in some replays that the content of noscript tags is rendering because during replay, scripts are not allowed.  I'd like to propose an option that either:

1) Prevents collecting the noscript tags
2) Prevents replaying the noscript tags

It's a given that they have script support or else the RRWeb recording library would not be working.  We tried the approach of removing the noscript tags before starting the recording, but pages contain plugins that load asynchronously after the recording has started and they populate noscript tags.

**Comment by Juice10** [comment]
I've bumped into this issue in the past and it turned out something had gone wrong that made sure this style wasn't injected in the replay iframe: 
https://github.com/rrweb-io/rrweb/blob/2b96a68e881695c54bbf6808e7df17c62adb1c21/src/replay/styles/inject-style.ts#L3

Could you check to see if this style is being set on your noscript tags correctly?

**Comment by ucjonathan** [comment]
@Juice10 Turns out the content being replayed contains an iframe for a chat client (live chat).  Inside that cross domain iframe where is a noscript tag that is showing up.  We're going to look at passing in the insertStyleRules to block that iframe from showing during the replay based upon it's id.  That will hopefully resolve our issue.
