### ISSUE TITLE
Add checkpoints during replay

### ISSUE THREAD

**Issue by Yuyz0112** [rrweb-io/rrweb#6]
We need to improve the 'play at any time' feature which supports rrweb-player's DND interactions.

Currently, we do this by introducing `sync` mode which will rebuild snapshot before time offset synchronously and then play under the timer. But this may cause a performance issue when we try to play at a large time offset.

For example, if we have 100 snapshots and we play in the third snapshot's time offset, we need to rebuild 3 snapshots synchronously which is fine. When we are trying to play at the 99th snapshot's time offset, we need to rebuild 99 snapshots synchronously which will block everything.

So the solution is to build checkpoints when we create a replayer. We may cache the result of rebuilding every 50 snapshots, so the maximize synchronously snapshots rebuilding number is 50.

**Comment by remisharrock** [comment]
Could you try the CODECAST player scrolling https://codecast.wp.imt.fr/codecast/  maybe you can find a way to have fast scrolling to any point in time in the source code https://github.com/France-ioi/codecast ?

**Comment by Yuyz0112** [comment]
@remisharrock Thanks, I'll take a look.

**Comment by remisharrock** [comment]
I found the name of the library that enables the fast seeking through the recording: Redux-Saga, as you can see in this file : https://github.com/France-ioi/codecast/blob/master/frontend/player/sagas.js 
It says that 
> // An instant has shape {t, eventIndex, state},
> // where state is an Immutable Map of shape

My guess is that the shape could be a VirtualDOM ?
Also the code has a lot of synchronization with the audio being played simultaneously.

By the way, you can try the recorder here https://codecast.france-ioi.org/v6/recorder by clicking the "guest" button , authorizing the use of your microphone, clicking the record button (red "start recording" and by typing some code in the editor (also selecting text, scrolling, compiling if it's C code and executing step by step etc...) 

Interesting here: when you click the pause button you can go back a little bit in the recording and start from this point.

Another thing interesting here: when you click the stop button, the audio is being compressed to mp3 client-side (using a javascript mp3 encoding library) ; 

Finally, when you click the save button, the JSON containing the events and the mp3 file is being sent to a server and you can play back the recording using the generated URL (playback link).

Can you try it and tell me what you think ?

Also try to seek during playback and also drag and drop the time cursor, you will see immediate changes, which I think is pretty cool ;)  

Hope that you can find a good solution from this project, in order to have this kind of reactivity when you seek through the recording during playback !

**Comment by remisharrock** [comment]
Also it looks like another dev has a slightly more updated CODECAST project and is working on it right now here https://github.com/pkrll/codecast

**Comment by remisharrock** [comment]
Any news on checkpointing or an approach to fast forward in any point in time very fast?

**Comment by buremba** [comment]
This would be a great feature IMO. We plan to use rrweb for product demos and definitely take advantage of it.
