### ISSUE TITLE
replayer modal rendering inconsistencies 

### ISSUE THREAD

**Issue by omairnabiel** [rrweb-io/rrweb#614]
I'm facing this issue where the same set of events when replayed, sometimes render the modals perfectly, and sometimes completely skips or renders it weirdly. The same events played twice and one time it renders everything perfectly and then when I replayed it again it played the same events with different result where modal isn't visible at all

**Comment by Juice10** [comment]
When you inspect the html of the replay can you see if the modal is added? There is a chance that the html is rendered but your styles aren't applied in which case it's probably related to https://github.com/rrweb-io/rrweb/pull/529

Could you share a gist of your events so we can investigate?

**Comment by omairnabiel** [comment]
Yea the html get's rendered. It's the issue with the styling. The styling for the main page is also off as you can see, not just in case of modal. Sometimes everything works fine, sometimes either one doesn't or both as in the images 

<img width="1022" alt="Screenshot 2021-07-06 at 10 52 47 AM" src="https://user-images.githubusercontent.com/13148988/124549227-4fa29a00-de48-11eb-9881-cfe48c4da717.png">

<img width="1017" alt="Screenshot 2021-07-06 at 10 56 47 AM" src="https://user-images.githubusercontent.com/13148988/124549639-dfe0df00-de48-11eb-8b19-c1cebf2011a9.png">

**Comment by omairnabiel** [comment]
Events JSON (it's not complete but will help). It produced around 1.4mb of events for a video of worth of 16 seconds. 😮 

[jira-rrweb-events.js.zip](https://github.com/rrweb-io/rrweb/files/6767719/jira-rrweb-events.js.zip)

**Comment by Juice10** [comment]
I'm going to spend some time on #529 today, and I'll see if that fix also solves your use case.

**Comment by Juice10** [comment]
@omairnabiel any chance I can get the full events.js? It seems cut off in the middle of an event unfortunately.
(happy to email with you if you don't want to share the full video with the whole internet).

**Comment by omairnabiel** [comment]
There you go. I generated this once again, has the same issues, although it's 6 seconds long

[jira-data.json.zip](https://github.com/rrweb-io/rrweb/files/6769920/jira-data.json.zip)

**Comment by Juice10** [comment]
@omairnabiel this is missing the first couple events. Any chance you could give me the whole 1.4mb, 16 second file?

**Comment by omairnabiel** [comment]
I don't have that now, I can record a longer session and email you

**Comment by omairnabiel** [comment]
I recorded the session again. This has all the events you'll need. Best of
Luck 🤞


>

**Comment by omairnabiel** [comment]
Not sure if you can help with this one too? Would you need events for this
as well?

https://github.com/rrweb-io/rrweb/issues/616

**Comment by omairnabiel** [comment]
Although after 1.0.2 styling is much more consistent and things have improved drastically 🥇 , but it still misses the rendering of modal at times

**Comment by Code-Crash** [comment]
Hi @Juice10,

I can see this is closed, still, there is an issue, sometimes I can see the class name is there, and the class definition is also there in the `<head><style>` still it does not apply to dom while rendering, do we have any issues like this? I tried but did not found, mostly it happens when we have huge CSS in `<head><style>`


Example: 

In this image, we can see, that the class name `ekDOGk` exists in the tag div.
<img width="360" alt="Screenshot 2022-09-15 at 3 16 05 PM" src="https://user-images.githubusercontent.com/5871757/190372582-9cc3655e-fd3a-45c8-9b14-28e3b31b4934.png">

In this image, we can see the style is there for this class, 

<img width="766" alt="Screenshot 2022-09-15 at 3 28 27 PM" src="https://user-images.githubusercontent.com/5871757/190375362-b6b74e70-cc06-4733-84ef-f52cd7a100e1.png">

however while rendering, we can see in the below image, that it is not applied.
 
<img width="542" alt="Screenshot 2022-09-15 at 3 34 38 PM" src="https://user-images.githubusercontent.com/5871757/190376666-9a09d4d5-df50-412f-8069-7ecd7ef9b549.png">

Please let me know if you know about this issue.

Note: Also, in replayer, I have enabled the interaction, and I deleted the style form head tag and added the style back in head tag, it's applying the CSS class and it's working.

**Comment by Code-Crash** [comment]
Hi @Juice10 ,

Do you have any idea in which scenario this can happen?

**Comment by Juice10** [comment]
@Code-Crash I've come across this before. Basically what is happening is the css rules have been removed through [`CSSStyleSheet.deleteRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/deleteRule). rrweb records this behaviour as well, but I have found (and solved) some bugs related to this in the past. Are you running rrweb 2.0.0-alpha.1?

**Comment by Code-Crash** [comment]
Hi @Juice10 

Thanks for the reply, I'm using [1.1.3](https://www.npmjs.com/package/rrweb/v/1.1.3)

Yes, it's tricky to debug it. 😅

**Comment by Juice10** [comment]
In that case definitely try 2.0.0-alpha.1 as it might contain a solution for the problem you are experiencing

**Comment by pravin-tiwari** [comment]
sure @Juice10 , let me try and I will get back to you accordingly.

Thanks.

**Comment by Code-Crash** [comment]
sure @Juice10 , let me try and I will get back to you accordingly.

Thanks.

**Comment by Code-Crash** [comment]
Hi @Juice10 ,

I was playing around with the `2.0.0-alpha.1` version and trying to record `app.appsmith.com` on this side, as it contains dynamic UI changes and all, saw a bunch of issues with recording, like duplicate DOM alerts, DOM got stuck and whatever I was doing was not able to record by `2.0.0-alpha.1` version as well.

Can you please check once to just record some sample app creation?

Thanks

**Comment by Juice10** [comment]
@Code-Crash could you share your events via a gist and then send a link to your https://rrwebdebug.com session for this? That makes it much easier for me to reproduce it

**Comment by Code-Crash** [comment]
Sure @Juice10 , I will create a debug session and update accordingly. Thanks.
