### ISSUE TITLE
add a blocked-hook (to determine which element should be blocked by users)

### ISSUE THREAD

**Issue by alienzhou** [rrweb-io/rrweb#62]
I am going to provide a frontend monitor sdk (includes replaying). For some reasons, I need to block some elements in the recording stage. 

Problems: I'd better not modify their code and dom (adding .rr-block). At the same time, they are probably not willing to modify and release a new version.

Is it possible to add  a hook? Then users can decide whether an element should be blocked without adding some class. (transparent to them and their website)

**Comment by Yuyz0112** [comment]
In the latest release, there is an option to configure the block class name https://github.com/rrweb-io/rrweb/blob/master/src/types.ts#L239

Some previous discussion:
https://github.com/rrweb-io/rrweb/issues/1
https://github.com/rrweb-io/rrweb/issues/23

Is the block hook still needed with this implementation? Since the block check may be triggered very frequently, personally I prefer some simple check instead of calling a function.

**Comment by alienzhou** [comment]
Thanks! After reading these, I agree that performance counts. And maybe this configuration helps. 

However, I meet a problem. I want to block two elements (with classname `.slide-banner` & `.feed-back`) in the page when recording.  It seems that I can just block one by `blockClass`.
Or I have to make the maintainers update their code.

**Comment by Yuyz0112** [comment]
Maybe extend the type of `blockClass` from `string` to `string | RegExp`?

**Comment by alienzhou** [comment]
Good idea. It helps.

**Comment by Yuyz0112** [comment]
@alienzhou in the `0.7.12` release the block class option now accept RegExp for checking. But there is still one thing left that we currently apply some styles for the blocked area when replaying, based on injecting some dynamic stylesheets into the `<iframe/>`.
And I think there is no way to do things like this on RegExp type class name matcher.
