### ISSUE TITLE
"Record Console Plugin" is unavailable

### ISSUE THREAD

**Issue by chylirk** [rrweb-io/rrweb#623]
First off, I wanted to say how much I appreciate that you've made this available to everyone. It's exactly what I'd been looking for, rather than something like Fullstory/logRocket/Asayer. Unfortunately, in the last week or so, the console recording functionality stopped working (although everything else is still fine).

After going through the guide and recipe pages a few times, I'm pretty sure it's related to the new plugin-based setup. When I changed the recorder configuration from `recordLog: true` to `plugins: [rrweb.getRecordConsolePlugin()]` I got the following error:

"Uncaught TypeError: rrweb.getRecordConsolePlugin is not a function"

I tried looking into the file at ```https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.js``` and I didn't see any `getRecordConsolePlugin` method, but I don't really know what to look for. Also, I did see that the method was exported [here](https://github.com/rrweb-io/rrweb/blob/39c8ba1a244880d4d154bd42571429cf76200fb7/src/plugins/console/record/index.ts), but I don't know typescript well enough to know where it goes from there.

For now, I'm using 0.9.14 and the older way of specifying that console logs should be events. Let me know if I could provide any more information, or if I'm misunderstanding something. Thanks!

**Comment by Yuyz0112** [comment]
Hi @chylirk 

If you are using CDN installation, you can use `rrweb-all.js` instead of `rrweb.js`, which is an all-in-one bundle of rrweb including all the plugins and features.

If bundle size is a consideration, you can include `https://cdn.jsdelivr.net/npm/rrweb@1.0.1/dist/plugins/console-record.min.js` to get the record plugin like this:

```js
rrwebConsoleRecord.getRecordConsolePlugin()
```

and include `https://cdn.jsdelivr.net/npm/rrweb@1.0.1/dist/plugins/console-replay.min.js` to get the replay plugin like this:

```js
rrwebConsoleReplay.getReplayConsolePlugin()
```

**Comment by chylirk** [comment]
Thank you! This resolved my problem
