### ISSUE TITLE
How to turn off scroll events?

### ISSUE THREAD

**Issue by svetlanabrennan** [rrweb-io/rrweb#636]
I can't seem to turn off scroll recording. 

I'm setting the "scroll" property to false and it still records scrolls:

` sampling:  {       
        mousemove: false,      
         mouseInteraction: {         
        MouseUp: false,         
        MouseDown: false,         
        Click: true,         
        ContextMenu: false,         
        DblClick: true,         
        Focus: true,         
        Blur: false,         
        TouchStart: false,         
        TouchEnd: true,       
    },       
     scroll: false,       
     input: 'last',    
     },
`

Version: 0.9.14

Thanks for your help,

**Comment by Yuyz0112** [comment]
You can only configure scroll sampling by its throttle threshold(in milliseconds) because you still need to capture scroll events to make sure the replay view is right after scrolling.

If you **really** want to turn off events, you can filter the event by type and source in the `emit` callback.

https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/dive-into-event.md
