### ISSUE TITLE
dropdown doesn't appear after replaying a recording 

### ISSUE THREAD

**Issue by SalahaldinBilal** [rrweb-io/rrweb#673]
The "Product" dropdown in the header doesn't appear after replaying the recording (it triggers on hover), neither will the message popup on the bottom right of the screen.

recording was done using the following userscript using greasemonkey v4.11, on Firefox 91.0 (64-bit), Windows 10 Verison 21H1, using the following code:
```
// ==UserScript==
// @name         New Userscript
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://www.fullsession.io/*
// @require https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js
// @grant        none
// ==/UserScript==

let events = [];

(function() {
    'use strict';
  events = [];
    rrweb.record({
        emit(event) {
           events.push(event);
          console.log(event);
        }
    });
  setTimeout(() => {
    console.log(JSON.stringify(events));
  }, 10000);
    // Your code here...
})();
```

Here's the replay page: 

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.css"
  />
  
  <script src="https://cdn.jsdelivr.net/npm/rrweb@latest/dist/rrweb.min.js"></script>
  <title>Document</title>
</head>
<body>
  <script>
    fetch("/data.json").then(res => res.json()).then(json => { //a json file that houses the recorded events
      const replayer = new rrweb.Replayer(json);
      replayer.play();
    })
  </script>
</body>
</html>
```
And here's a copy of outputted events : https://abbyani.xyz/fQ3WH.json

After waiting 10 seconds and playing the outputted events, the drop down menu and the popup wont show at all in the replay.

**Comment by mariendev** [comment]
Normal dropdowns are managed by the operating system itself and thus not recordable. You should make custom HTML dropdowns or accept that you don't see it.

**Comment by Yuyz0112** [comment]
@SalahaldinBilal 

Because the dropdown was controlled by the `:hover` CSS property comes from this stylesheet(https://d1aj3l0me5nhq7.cloudfront.net/wp-content/cache/minify/35dbf.css).

Since this is a cross-origin stylesheet, rrweb is not allowed to inline the content of the stylesheet and do the [hover hack](https://github.com/rrweb-io/rrweb/blob/master/docs/replay.md#simulation-hover).

You can
1. change the stylesheet to a same-origin URL if possible.
2. run a backend program, which downloads the stylesheet in the backend and uploads it to a same-origin URL with the replayer.
