### ISSUE TITLE
possible to support mobile?

### ISSUE THREAD

**Issue by Gardener-Yuan** [rrweb-io/rrweb#71]
Recording the mobile page and replaying is not prefect

**Comment by Yuyz0112** [comment]
Thanks for the feedback. Could you give more description of which part is not perfect or provide a sample mobile website.

**Comment by Gardener-Yuan** [comment]
Touchmove event has no pointer display when replay like PC

**Comment by marcospassos** [comment]
It looks like RRWeb [is not listening](https://github.com/rrweb-io/rrweb/blob/master/src/record/observer.ts#L305) to the`touchstart`, `touchend` and `touchmove` events.

@Yuyz0112 is there any special reason to do not listen to these events?

**Comment by Yuyz0112** [comment]
@Gardener-Yuan @marcospassos Now it supports:)

**Comment by marcospassos** [comment]
@Yuyz0112 could please clarify what is the purpose of the new `MouseInteractions`? TouchMove_Departed` as it's not even used? I believe the commit introduces an inconsistency: the `TouchMove` is analogous to the `MouseMove`, so it should be a new `IncrementalSource` instead of a new `MouseInteractions`. Making this distinction allows consumers (including the replay application) to distinguish between mouse move events and touch move events.

**Comment by Yuyz0112** [comment]
@marcospassos 
`MouseInteractions` may become a little misunderstanding because of its naming. Actually, it's an enum contains interaction events we listened.

Previously we record touch move like a normal interaction, but then we found it should be recorded like mouse move. So we need to remove touch move from the normal interactions enum.
But typescript's enum will be compiled to number in runtime, that's why we keep TouchMove_Departed in the enum with a `Departed` suffix to indicate the event listener do not listen to it.

Instead, we record touch move in the same way of mouse move, which has a two-level throttle implementation. And you are right, we could add a flag to show its a mouse move event or a touch move event.
