### ISSUE TITLE
not recording <header> or <amp> components

### ISSUE THREAD

**Issue by omairnabiel** [rrweb-io/rrweb#730]
Recorded a session on this website (https://dictionary.cambridge.org/dictionary/english) and the header seems to be missing from the replay. Not sure if it's because of amp binding or just simply the fonts not loading due to CSP policy

<img width="677" alt="Screenshot 2021-10-14 at 2 59 47 PM" src="https://user-images.githubusercontent.com/13148988/137296240-1e74f200-4099-4800-9d1c-1e375d83f720.png">

**Comment by omairnabiel** [comment]
Here it is -> https://rrwebdebug.com/play/index.html?url=https%3A%2F%2Fjsonblob.com%2F905371464992309248&version=0.7.8

**Comment by Mark-Fenng** [comment]
@omairnabiel You are right. After some debug work, I found this problem is caused by missing the font file.
The icons of this website are located at https://dictionary.cambridge.org/external/fonts/cdoicons.woff?version=5.0.250 . 
In the replayer, the request for this URL is blocked because of CSP policy.
