### ISSUE TITLE
It appears node mutations are randomly omitted from incremental snapshot

### ISSUE THREAD

**Issue by baransu** [rrweb-io/rrweb#850]
On the following demo website `rrweb` fails to record `Toolbar` element:
- CodeSandbox: https://codesandbox.io/s/jam-sandbox-299kuq?file=/pages/index.vue
- Demo: https://299kuq.sse.codesandbox.io/

Here is the HTML of the element.
```html
<div data-v-2a183b29="" data-v-314f53c6="" class="p-4">
  <!--fragment#e5605832f3#head-->
  <div data-v-79fc3c40="" fragment="e5605832f3" class="sticky-sentinel sticky-sentinel__top" style="--sticky-offset:0px;"></div> 
  <div data-v-2a183b29="" fragment="e5605832f3" id="toolbar">Toolbar</div>
  <!--fragment#e5605832f3#tail-->
  <div data-v-2a183b29="" class="min-h-[200vh] w-full bg-red-100 p-4">...</div>
</div>
```

Sometimes (I failed to pinpoint why) nodes between `<!-- fragment>` get omitted when handled by `MutationBuffer`. It looks they are passed to https://github.com/rrweb-io/rrweb/blob/bd144be39be799dc598e11377bb5356b0752e986/packages/rrweb/src/record/mutation.ts#L260 function but get dropped at this point https://github.com/rrweb-io/rrweb/blob/bd144be39be799dc598e11377bb5356b0752e986/packages/rrweb/src/record/mutation.ts#L275.

When I'm checking `parentNode` and `nextSibling` or the `id="toolbar"` node it looks like `parentNode` is not in the document (I'm not sure why because when I hover over an element inside console logged element inside dev tools target element is correctly inside DOM - just parent is missing). `nextSibling` is `<!--fragment>` comment.

Let me know if I can provide more detailed information or if you can point me to finding a workaround or a fix for this problem.

**Comment by Mark-Fenng** [comment]
@baransu seems like the parentNode of 'toolbar' is an element 
<img width="582" alt="image" src="https://user-images.githubusercontent.com/27533910/157594816-aa4c2484-abed-4673-a837-969083a9939b.png">.
But this node isn't in the document however it's parentNode 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/27533910/157594949-48f6da72-08a9-422a-a9b2-3cb74eeaacc4.png"> is exactly the parentElement of 'toolbar'.
Even more strange, 'toolbar''s parentNode doesn't contain 'toolbar' itself!
<img width="236" alt="image" src="https://user-images.githubusercontent.com/27533910/157595365-685d6821-edfb-4697-830b-24fd8813939c.png">

I think you use some tricks to achieve this feature but break the dom standards. So maybe you have to change your implementation because this issue seems to exceed rrweb's range.

**Comment by baransu** [comment]
Thank you for debugging! I haven't spotted the difference between `parentNode` and `parentElement`. I don't understand why it's happening (it may be `vue-fragment` fault).

**Comment by baransu** [comment]
Is it possible for `rrweb` to use `parentElement` optionally as a fallback to `parentNode`?
