### ISSUE TITLE
default export wrongly advertised in guide?

### ISSUE THREAD

**Issue by dphuang2** [rrweb-io/rrweb#95]
### Record

**If you only included the record code with `<script>`**, then you must use the global variable `rrwebRecord` instead of `rrweb.record`.
The following sample code will use the variable `rrweb` which is the default exporter of this library.

```js
rrweb.record({
  emit(event) {
    // store the event in any way you like
  },
});
```

____________________________________________________

Does this section imply that the 'rrweb' variable is the default export of the library so users can import the library as: `import rrweb from 'rrweb';`? If this is true, it is confusing and probably the reason why #67 was made. 

Thanks for clarifying and maybe this should be clearer by differentiating browser and node.js usage.

**Comment by Yuyz0112** [comment]
Hi @dphuang2 
It's because rrweb has three types of exports: `iife` for the browser, `commonjs` and `es-modules`.

So when you are using the `iife` export(with <script>), then you can access the `rrweb` which is a global variable.
And if you are using `import {} from 'rrweb'` which is a es-modules syntax, then you can not use the default exporter because rrweb does not export something as default.

So this is mainly some module system things in different standards, and I'm not sure what's the best description for every scene.
Any doc improvement is welcomed!
